favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://d8cardz.com/themes/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  paragraph_social_media_theme: 8000
